### ISSUE TITLE
Feature request: add pull of "Einheiten" and old data

### ISSUE THREAD

**Issue by AleXSR700** [Ludy87/ecotrend-ista#1]
Hello @Ludy87 

thank you for working on an ista Ecotrend integration for Home Assistant.

I wanted to give it a try and added your repository to HACS, installed and then added a package with the config.

The first data has been pulled. Excellent!

Would it be possible to pull all data available, i.e. old data and also the "Einheiten" that were consumed?
This would allow to also track the conversion being performed from "Einheiten" to kWh as one is the "Verbrauchseinheiten" which can be read locally from the sensors.

Maybe, if you are a member and feel like it, we can also discuss in a dedicated thread in Home Assistant Community Forum? I could imagine more people being interested in this :)

Thank you and looking forward to the official HACS release
Alex

**Comment by AleXSR700** [comment]
The first data has been pulled. Excellent!

Would it be possible to pull all data available, i.e. old data and also the "Einheiten" that were consumed?
This would allow to also track the conversion being performed from "Einheiten" to kWh as one is the "Verbrauchseinheiten" which can be read locally from the sensors.

**Comment by AleXSR700** [comment]
Thank you for taking my requests into account so quickly!

Testing right now :)

About "Einheiten" , I think there may have been a misunderstanding. I meant the "Verbrauchseinheiten" which are simply listed as "Einheiten" (see picture). The unit is correctly pulled (in my case kWh).

![Screenshot_20220508-090310_ista EcoTrend.jpg](https://user-images.githubusercontent.com/57034871/167284188-cde78ce4-e345-49ff-a34e-b55fb12f53cf.jpg)

**Comment by Ludy87** [comment]
@AleXSR700 du kannst jetzt zwischen Einheiten und kwh wählen, um kwh angezeigt zu bekommen muss `unit: "kwh"` gesetzt werden sonst sind es nur Einheiten

**Comment by AleXSR700** [comment]
Ah, verstehe.
Und wenn ich beides möchte?
Wird dann ein zweiter Sensor erzeugt?

**Comment by Ludy87** [comment]
Nein, das wird noch kommen;)

**Comment by Ludy87** [comment]
@AleXSR700 du kannst aber auch jetzt schon beide Werte auslesen, da beides übertragen wird. Du müsstest dir ein Template o.ä. anlegen.

**Comment by Ludy87** [comment]
> Zudem wird nur die Verbrauchseinheit abgerufen, nicht aber die kWh, wenn man keine Angabe in der config macht.

So ist es, füge `unit: "kwh"` hinzu https://github.com/Ludy87/ecotrend-ista#optional

Die Entity `warmwater_XXXXXXXXX` und `heating_XXXXXXXXX` zeigt immer die aktuelle Auswertung vom Vormonat an.

**Comment by AleXSR700** [comment]
Aber wenn man pro Monat eine entity hat, dann lassen sich die Daten nicht mehr auswerten. Die Idee wäre ja, dass man eine Entity für "Einheiten" und eine für kWh hat und in diesen beiden Entities alle Daten bereitliegen.
Sonst müsste man seine Plots ja jeden Monat um eine weitere Entity ergänzen, nur um einen neuen Datenpunkt zu haben.

Außerdem spamt einem dann ista-ecotrend die Entities voll ;-)


Zur Config:
Und wenn man beides möchte? Gibt man dann

```unit:
 - kWh
 - Einheiten```

an?

**Comment by AleXSR700** [comment]
Nunja, das Problem ist, dass der "normale" Sensor nur aktuelle und zukünftige Daten holt. Da die Daten aber auf dem Server zur Verfügung stehen, wäre es ja am besten, wenn er alle Daten vom Server abrufen würde. So hätte man im Falle eines Datenbankcrashes o.ä. keine Probleme.
Man hätte immer alle Daten, die auf dem Server liegen. Egal ob alt oder neu.

Für die erzeugten, monatlichen Sensoren sehe ich spontan keinen Anwendungsfall. Aber das ist nur persönliche Überlegung. Andere möchten vielleicht einen Sensor pro Datenpunkt :-)

Deshalb, aus meiner ganz persönlichen Sicht, bräuchte es nur einen Sensor pro Einheit (sprich einen für Einheiten und einen für kWh). Und dieser Sensor ruft alle alten sowie künftigen Daten automatisch ab. So hat man immer alle vergangenen und künftigen Daten zu einem Parameter in nur einem Sensor und kann diesen wunderbar plotten.
Und wenn man Verbrauchseinheiten und kWh in je einem Sensor hat, kann man die korrelation beider mit nur zwei Sensoren plotten.

**Comment by AleXSR700** [comment]
Du meinst, dass man keinen Datumswert schreiben kann?

**Comment by Ludy87** [comment]
Ist mir nicht bekannt

**Comment by Ludy87** [comment]
> Zur Config: Und wenn man beides möchte? Gibt man dann
> 
> ```
> unit:
>  - kWh
>  - Einheiten
> ```
> 
> an?

Dazu ein Template erstellen: https://github.com/Ludy87/ecotrend-ista#template und schon kann es los gehen

**Comment by AleXSR700** [comment]
> Ist mir nicht bekannt

So wie es aussieht wäre es möglich, wenn die Integration die Werte direkt in die DB schreibt. Dann könnten auch alte Werte abgerufen und gespeichert werden.
Das wäre vor allem bei neuen Usern und auch bei Wiederherstellungen o.ä. interessant.

Da sich auch recht oft Dinge im HA core und der Datenbank ändern, wäre das sehr nützlich.

**Comment by Ludy87** [comment]
Ich werde mich mit der Datenbank beschäftigen, wird aber nicht sofort passieren, da meine andere Integration Momentan mehr Zeit beansprucht, als mir lieb ist.

**Comment by AleXSR700** [comment]
Ich habe die Tage noch ein wenig probiert und man kann den Datenbankwert nachträglich ändern. Es müsste also möglich sein den Bezugszeitpunkt in die Datenbank zu schreiben anstatt des Datums der Erzeugung des Datensatzes.

Leider konnte ich noch nicht in Erfahrung bringen wie man das dann bei einer Integration macht.

**Comment by Ludy87** [comment]
Wie hast du es denn angestellt?

**Comment by ekeih** [comment]
If I understand it correctly https://community.home-assistant.io/t/import-old-energy-readings-for-use-in-energy-dashboard/341406/9 shows how integrations can add data with a different timestamp than `now`.

**Comment by Firehome2022** [comment]
Hallo Ludy87.
erst einmal vielen dank für die Integration. Ich habe sie gestern entdeckt und bin froh dass es eine Integration für ISTA gibt.
Ich habe den Eintrag in die configuration.yaml übernommen. Das template liegt in der template.yaml. 
Mein Problem ist das anscheinend keine Daten im Home Assistant ankommen. Die Anmeldung mit dem ISTA User/Passwort über die Ecotrend App funktioniert also müssen die User Daten passen. Wenn ich es richtig verstehe müssten doch bei den Entitäten neue Entitäten zu finden sein oder sehe ich das falsch. Ich bin noch nicht so lange mit HA dran daher hoffe ich das die Frage / Problem nicht zu blöd ist.
Gruß Firehome

**Comment by AleXSR700** [comment]
@Ludy87 : do you think you will be able to pull and process old data?

**Comment by Ludy87** [comment]
@AleXSR700 Getting the old data isn't the problem, but integrating it is. I've been trying to integrate this for a long time, and the database keeps breaking. As soon as I have a solution I will incorporate it.

**Comment by AleXSR700** [comment]
Hello,
any luck getting the old data written to the database?

**Comment by Ludy87** [comment]
> Hello, any luck getting the old data written to the database?

I think I won't try it until HA provides it.

**Comment by AleXSR700** [comment]
Is there a FR or PR for that?
