### ISSUE TITLE
Documentation: where to add the template

### ISSUE THREAD

**Issue by jklmnn** [Ludy87/ecotrend-ista#10]
Sorry for the dumb question, but where is the template supposed to go? I tried placing it in `configurations.yaml` at the top level, under `ecotrend_ista:`, under `sensor:`, under `platform: template` and so on, everything throws errors. I was also unable to find any documentation in homeassistant itself about what to do with templates formatted in that kind.

**Comment by Ludy87** [comment]
Easily in the configuration.yaml file

Check: https://github.com/Ludy87/ecotrend-ista#basis-configuration

**Comment by jklmnn** [comment]
Doing that I get the following error:
```

                    Error loading /usr/lib/homeassistant/.homeassistant/configuration.yaml: while parsing a block mapping
  in "/usr/lib/homeassistant/.homeassistant/configuration.yaml", line 3, column 1
expected <block end>, but found '-'
  in "/usr/lib/homeassistant/.homeassistant/configuration.yaml", line 24, column 1
```

**Comment by Ludy87** [comment]
@jklmnn please take a screenshot of the configuration

**Comment by jklmnn** [comment]
I found the issue. The doc says that it has to start with a `-` while I had to remove it. So I got it working and my current configuration looks like this (see the missing `-` infront of `template`):
```yaml
template:
  - sensor:
      - name: ECO Heizung Einheiten
        unit_of_measurement: "Einheiten"
 ...
```
