### ISSUE TITLE
Documentation: semantic of year and yearmonth

### ISSUE THREAD

**Issue by jklmnn** [Ludy87/ecotrend-ista#11]
What is the semantic of `year` and `yearmonth`. From what I can see it selects which data to pull. Does that mean I have to update my configuration in regular intervals?

**Comment by Ludy87** [comment]
with `year` is created for each month of the entire year e.g. 2022

With `yearmoth` months can be created separately if desired.

see: https://github.com/Ludy87/ecotrend-ista#optional
