### ISSUE TITLE
Cannot add integration with 2FA

### ISSUE THREAD

**Issue by saschabrockel** [Ludy87/ecotrend-ista#156]
The manual is not really clear for the last step. I did everything and know have to type in my credentials and login URL and 2FA. But what should I paste in 2FA? No matter what I try, it doesn't work.

It always returns: Unerwarteter Fehler. Unexpected error in English.

**Comment by Ludy87** [comment]
Hi, bist du der Anweisung gefolgt: https://github.com/Ludy87/ecotrend-ista/blob/main/TWO_FACTOR_AUTHENTICATION_DE.md

**Comment by saschabrockel** [comment]
Jetzt gab es einmal den folgenden Fehler in den Logs:
`('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`

Seitdem wieder nur Unerwarteter Fehler als Popup und nichts in den Logs.

**Comment by Ludy87** [comment]
Ista ist da etwas komisch im Verhalten, du muss die Integration neu laden.

![image](https://github.com/Ludy87/ecotrend-ista/assets/4592558/6358bceb-bb52-43a9-b99a-1c85cf0fcb7d)

**Comment by Ludy87** [comment]
Bin davon ausgegangen, durch die Fehlermeldung: ```('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))```

Okay, dann  nochmal von vorne.

Hast du den Sensor angelegt:
```
# Example configuration.yaml entry
sensor:
  - platform: otp
    token: KEY_FROM_ECOTREND
```

`KEY_FROM_ECOTREND` wird hier erklärt: https://github.com/Ludy87/ecotrend-ista/blob/main/TWO_FACTOR_AUTHENTICATION_DE.md#klicke-auf-hat-der-scan-nicht-funktioniert-unter-dem-qr-code

**Comment by saschabrockel** [comment]
Ja, habe ich. Habe den auch in der Oberfläche:
![image](https://github.com/Ludy87/ecotrend-ista/assets/33376463/1d94f259-16a7-48d7-b2d5-deb7c33fdcda)

**Comment by Ludy87** [comment]
Das "Gerät" (der Sensor zeigt dir alle 30sec einen neuen Code) hast du dann auf der Seite von Ista registriert? https://github.com/Ludy87/ecotrend-ista/blob/main/TWO_FACTOR_AUTHENTICATION_DE.md#schreibe-einen-namen-in-ger%C3%A4tename-bevor-du-den-code-von-otp-sensor-kopierst-danach-kopierst-du-den-generierten-code-und-f%C3%BCgst-ihn-ein-achtung-der-code-ist-nur-30sec-g%C3%BCltig

**Comment by saschabrockel** [comment]
Du meinst, dass ich den Code in Home Assistant durch den Neustart habe und dann auf der Ista Seite quasi schonmal den Namen vorausgefüllt habe und dann nur noch den Code aus Home Assistant auf die Ista Seite kopiert habe und dann quasi abgeschickt. Und das eben innerhalb der 30 Sekunden Gültigkeit oder?

Das habe ich definitiv gemacht. Ich glaube sonst wäre er ja auch nicht hier oder:
![image](https://github.com/Ludy87/ecotrend-ista/assets/33376463/e227f885-c914-40ca-9adb-efce6ace9472)

Ist es ein Problem, da ich zwei Stück habe?

**Comment by saschabrockel** [comment]
@Ludy87 soll der Daumen hoch heißen, dass es ein Problem ist? 😄

**Comment by saschabrockel** [comment]
Will nicht nerven, aber gerade die letzte Antwort zu wissen wäre noch gut 😄

**Comment by Ludy87** [comment]
Ich weiß momentan was das Problem ist. Aber es sind erstmal alle Schritte getan die getan werden müssen.

**Comment by saschabrockel** [comment]
Hat leider nichts gebracht. Hab geupdated, HA neugestartet und es geht nach wie vor nicht.

**Comment by Ludy87** [comment]
Sorry das es nicht funktioniert, bin etwas verzweifelt. Leider kann ich es auch nicht erneut durchspielen.

**Comment by saschabrockel** [comment]
Ich kann gerne versuchen zu helfen, soweit ich kann. Also jedenfalls wenn es um das Testen von Pre-Release Versionen geht etc.

**Comment by Ludy87** [comment]
@habandy ich habe die Begriffe verwendet, die auch ectrone verwendet um keiner Verwirrung zu verursachen.

**Comment by Ludy87** [comment]
Hat HA die richtige Zeit? Wenn die Zeit vom Server nicht stimmt kann es auch zu Fehler führen.
