### ISSUE TITLE
Feature request: Set pull intervall

### ISSUE THREAD

**Issue by AleXSR700** [Ludy87/ecotrend-ista#2]
Hello @Ludy87 ,

I saw that data is being pulled regularly. Would it be (or is it maybe already) possible to set this interval manually?

Thank you for your consideration.

Alex

**Comment by Ludy87** [comment]
If you put the interval over the value of 24 hours, it could happen that you miss a day. The best solution would currently be 11:59 hours.

**Comment by AleXSR700** [comment]
Miss a day of what?
Do they also offer daily data for some devices?

Would it not be possible to define a scan_interval in the config?
Heating data e.g. is monthly.  So not mich point in checking daily.

Alternatively (and maybe linked to by other request), would it not be possible to check daily but only write new data point if the data is from a month that is not yet im database?

**Comment by Ludy87** [comment]
You can use scan_interval

**Comment by Ludy87** [comment]
@tribut I think if Hassio is restarted, the current data will only be fetched a day later. 
You could possibly use 11 h 59 min 59 sec to push it to the limit.

**Comment by AleXSR700** [comment]
I thought that the scan_interval is normally started at reboot. So the clock resets itself.

But I could well be mistaken because I set the scan_interval to 60 seconds so I can test pulling 2022 data and it so far has not updated the sensor at all.

But this is strange to me. Why would it not apply the new scan_interval until the next day?

**Comment by Ludy87** [comment]
You misunderstand that, if the interval is set to 24 hours and you start Hassio now at 1 p.m., the data will not be queried again until 1 p.m.
