### ISSUE TITLE
no json returned

### ISSUE THREAD

**Issue by ulbricht-inr** [Ludy87/ecotrend-ista#22]
Hi, i get the error:
```
File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api.prod.eed.ista.com/consumptions?consumptionUnitUuid=XXXX')
```

(i replaced my UID with XXXX)

Is this an bug, or did they changed their API? The URL did not return json... 
Thank you :)

**Comment by ulbricht-inr** [comment]
works after upgrading HA to 2022.10.5. 
A restart of HA via web interface was necessary after starting the docker container...

**Comment by Ludy87** [comment]
@ulbricht-inr the error is a bug, but this is server-side. I'm currently working on adding the cost when available. After that I'll start catching the errors.
