### ISSUE TITLE
Energy Page Integration.

### ISSUE THREAD

**Issue by Mitsuma** [Ludy87/ecotrend-ista#26]
Hello there,
it seems ista is back running.
HA has added water usage to the Energy Tab, so I wonder if this can be added as a compatible thing.
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics 

Not sure how this works with HACS integrations, if at all.
Just wondering if this can be done.
Thanks for this nice integration.

**Comment by Ludy87** [comment]
![image](https://user-images.githubusercontent.com/4592558/202924419-1445b395-ce7d-4020-9b67-d00d63ba6f25.png)

a service update: the integration is taking shape. It's more work than you think.

Please me if this is a misrepresentation.

**Comment by Wlad2288** [comment]
Thanks @Ludy87 ! This looks quite promising.
Is there any way I can use this already?

**Comment by Ludy87** [comment]
Whenever I think it's working - there's an error, negative values are registered or the database is flooded
