### ISSUE TITLE
warmwater_unit not honored in the sensor graph

### ISSUE THREAD

**Issue by lawa42** [Ludy87/ecotrend-ista#28]
The change to m³ is somehow not honored in the sensor plot. As you can see from the screenshot below it reports the correct  m³ value but the y-axis of the plot shows kWh but claims to be m³

![grafik](https://user-images.githubusercontent.com/17469152/201526825-58d0b07c-9790-4ed0-b6ce-5d5e65107fb4.png)

**Comment by Ludy87** [comment]
Hi, in version 2 I will see why that is. Unfortunately it will take some time. I miss the time when ISTA was down.
