### ISSUE TITLE
Unfortunately, it no longer works after the update

### ISSUE THREAD

**Issue by selzilla** [Ludy87/ecotrend-ista#38]
Unfortunately, it no longer works after the update. HA immediately throws up an error message. I had to remove the entry in configuration.yaml.

Unable to install package pyecotrend_ista==1.0.37: ERROR: Cannot install pyecotrend-ista==1.0.37 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.3 -> 22.3.1 [notice] To update, run: pip install --upgrade pip
03:59:49 – (FEHLER) util/package.py -

**Comment by Ludy87** [comment]
Behoben mit Core 2022.12.3 https://github.com/home-assistant/core/commit/858cf8ca335a1ecc34b8a6e95fba9a79bfda5b3c

https://github.com/Ludy87/ecotrend-ista/issues/36#issuecomment-1346220135
