### ISSUE TITLE
Login domain request

### ISSUE THREAD

**Issue by TheRealRWJ** [Ludy87/ecotrend-ista#41]
# info 
Many thanks for this ecotrend_ista integration. Unfortunately i am unable to use it
Ista is available in different countries.

# Error
When I use my credentials of mijn.ista.nl, (the dutch website) The Home assistant throws a login error and refers me to https://ecotrend.ista.de/error , assuming the script tries to login on the https://ecotrend.ista.de server.

# Question
Is it an option to change the code so the script tries to login on https://mijn.ista.nl
I am happy to troubleshoot is it doesn't work

# OR Request
Can you please add the option to enter a domain to login on another (dutch)  ista web server.

**Comment by Ludy87** [comment]
The data structure is different on the site, so I'll have to see how best to implement this. Either integrate it into the main integration or I create a complete extra integration.

**Comment by TheRealRWJ** [comment]
Thanks Ludy for your swift reply

Let me know if you need someone to troubleshoot

Greetings Richard

**Comment by Ludy87** [comment]
@TheRealRWJ is there an Android app for the Netherlands?

**Comment by TheRealRWJ** [comment]
Yes there is, and you can find it here:
https://play.google.com/store/apps/details?id=com.companyname.ista.nl.app&hl=en&gl=US&pli=1

**Comment by Ludy87** [comment]
Thanks, the login routine is different from the master one, so I need to find a way and android applications are good for finding a way.

Maybe I can find a way to integrate the Netherlands.

**Comment by TheRealRWJ** [comment]
I don't use the android app, but I gathered some details from the webpage though.
I hope this helps

I can only test heating, because I did not find a water meter, unless it is build in somewhere in the walls which seems unlikely.



The https://mijn.ista.nl/Home page shows the sum of usage of all radiators and a building average usage (which I would like to use)

The https://mijn.ista.nl/Home/Graph page shows a graph of the usage per radiator

At last the https://mijn.ista.nl/Home/Data page shows info below for every radiator.

Bedroom	422xxxx87	781 units	
			
	Radiatornumber	1	
	Order	1	
	End value	1.050	
	Begin value	0	
	Difference	1.050	
	Conversionfactor	0.875	
	Multiply	1	
	Consumption	919 units	
	Reduction %	15	
	Begin date	01-01-2022	
	End date	13-12-2022	
		


Units appears to be the interger a rounding of consumption / reduction

End value and begin value seem to be the beginning of the year and current value
End value / conversionfactor seems to be consumption rouded

I have no clue why what the difference is of End value and difference

I started living in this apartment in december 2021, so it the ista devices were not new
Maybe I will know on january first 2023


Questions:
Does your python script do some calculation of usage per day?
I really like to compare it with the outside temperature.

Does your script read the building average? I would like to be able to compare my neighbours with others
I will be storing the data in Influxdb to create long term Grafana Graphs


Thanks in advance

**Comment by Ludy87** [comment]
Thank you for your data, I have more questions about that later.

The integration can only work with the data that is partially provided by ista.

When I look at your data status, it will not be up to date.

These are the values ​​that can be read out if they are available.

```
Room
Meter number
Consumption
Radiatornumber
Order
End value
Begin value
Difference
Conversionfactor
Multiply
Consumption
Reduction %
Loss
Begin date
End date
Billing period:
Compare:
Service:
Billing period:
Measurement period:
Compare to billing period:
Compare to measurement period:
Dwelling:
Total
```

**Comment by TheRealRWJ** [comment]
Happy holidays

**Comment by mikastrup** [comment]
Same error here but for the danish version.

I can login on the ista Ecotrend APP (Android) but don't know if it is only the danish webserver.

maybe possible worldwide (worth a shot)
https://play.google.com/store/apps/details?id=dk.ista.IstaUi

**Comment by Ludy87** [comment]
@mikastrup is there a website with dashboard?

**Comment by TheRealRWJ** [comment]
Hi  Ludy,
Happy new year.

Yes, there is a dashboard. 
The url is https://mijn.ista.nl/Identity/Account/Login

What else  would you like to know?

**Comment by ggonmar** [comment]
+1 on this request, extending it from out of the Netherlands: 
Ista is extremely popular in Spain, but this integration doesn't seem to work with our platform -> https://www.ista.com/es/oficina-virtual-ista/

I'd be happy to try to help develop this, but I don't even know where to start...

**Comment by TheRealRWJ** [comment]
Hi Ludy,

I do not mean to pressure you. doe you have any indication when you will be able to release this?

thanks in advance

**Comment by sqren** [comment]
Hi there

Thanks for the awesome work so far @Ludy87 !

I would also love to integrate Ista into Home Assistant with your integration but I'm located in Denmark and I'm also seeing authentication problems:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyecotrend_ista/pyecotrend_ista.py", line 57, in __login
    raise LoginError(await response.json())
pyecotrend_ista.exception_classes.LoginError: Login fail, check your input! {'key': 'unauthorized-request', 'message': None}
```

To add some details for the Danish version of Ista:
Web: https://www.istaonline.dk/Login.aspx
Android app: https://play.google.com/store/apps/details?id=dk.ista.IstaUi

I'd be happy to provide you with credentials to the Danish version if that can help you debug this

**Comment by TheRealRWJ** [comment]
Hi Ludy,

Are you still working on this issue?

Thanks in advance.

**Comment by Ludy87** [comment]
Hello, yes I'm still working on it, but I don't have much time at the moment - it's more complex than I thought.

**Comment by ggonmar** [comment]
do let us know if we can help!
