### ISSUE TITLE
Compatibility with ISTA-Webconso

### ISSUE THREAD

**Issue by DW-homeassistant** [Ludy87/ecotrend-ista#73]
Hi, 

Is there any hope that this extension become also compatible with https://www.ista-webconso.fr/ ?

**Comment by Ludy87** [comment]
Is the service the same as https://ma-consommation.ista.lu/

**Comment by DW-homeassistant** [comment]
> Is the service the same as https://ma-consommation.ista.lu/

Well, the luxembourg website rederects the users to ISTA EcoTrend on google play,.. we can assume the HA extension may for luxembourg users ? (maybe with the accurate website)

**Comment by Ludy87** [comment]
the fact that the redirect leads to https://ecotrend.ista.de/ is very good, so you can log in with the Luxembourgish login data.

ista will soon be converting your system, i don't know the extent yet - i have to hope that you don't lock us out.
