### ISSUE TITLE
Possible to get this to work in Norway?

### ISSUE THREAD

**Issue by zyntax9999** [Ludy87/ecotrend-ista#91]
Hi,

I have Ista Ecotrend in Norway, using this login page: https://www.istaonline.no/Login.aspx
Is it possible to get this work in Norway also?

**Comment by jm-cook** [comment]
I would also like this. 

The istaonline.no portal requires a username to login, my username is not an email address.

**Comment by jm-cook** [comment]
> I would also like this.
> 
> The istaonline.no portal requires a username to login, my username is not an email address.

The android app available for Norway is the same as the danish one: https://play.google.com/store/apps/details?id=dk.ista.IstaUi

**Comment by truffles003** [comment]
> > I would also like this.
> > The istaonline.no portal requires a username to login, my username is not an email address.
> 
> The android app available for Norway is the same as the danish one: https://play.google.com/store/apps/details?id=dk.ista.IstaUi

App seems to use the following URL, when connecting: service.istaonlinebeta.dk

**Comment by midlan** [comment]
Same question here, but for Czech support. My login is working in the android app: https://play.google.com/store/apps/details?id=dk.ista.IstaUi
